name: hq_study
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 国际化支持
  flutter_localizations:
    sdk: flutter
  # 国际化库
  intl: ^0.19.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # 网络请求
  dio: ^4.0.6
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  # 状态管理
  provider: ^6.0.0
  #瀑布流
  flutter_staggered_grid_view: ^0.6.2
  #偏好设置插件，需要重新运行项目，将插件安装完成
  shared_preferences: ^2.0.15
  fluttertoast: ^8.1.1
  ext_video_player: ^0.1.2
  # video_player: ^2.4.7
  # 使用本地插件
  hq_device_info:
    # 指定本地插件目录
    # path: ../hq_device_info
    # 指定plugin git 地址添加依赖
    git:
      url: https://github.com/HeHuiqi/hq_device_info.git


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # 添加图片
  assets:
    - images/pic0.jpg
    - images/pic1.jpg
    - images/pic2.jpg
    - images/pic3.jpg
    - images/pic4.jpg
    - images/pic5.jpg
    - images/pic6.jpg
    - images/pic7.jpg
    - images/pic8.jpg
    - images/pic9.jpg
    - images/pic10.jpg
    - images/pic11.jpg
    - images/pic12.jpg
    - images/pic13.jpg
    - images/pic14.jpg
    - images/pic15.jpg
    - images/pic16.jpg
    - images/pic17.jpg
    - images/pic18.jpg
    - images/pic19.jpg
    - images/pic20.jpg
    - images/pic21.jpg
    - images/pic22.jpg
    - images/pic23.jpg
    - images/pic24.jpg
    - images/pic25.jpg
    - images/pic26.jpg
    - images/pic27.jpg
    - images/pic28.jpg
    - images/pic29.jpg
    - images/lake.jpg
    - images/flippers-alpha.png
    - images/icon_et_delete.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
